path_dataset: './data/'
path_models: ''
path_results: './out/results/'

start_idx: 0
step_idx: 3
end_idx: 108

reverse: False
task_type: "alt_goal"
use_gt_localization: True
env: "sim"

split: "val"
threshold_goal_distance: 1.0
max_start_distance: "hard"
max_steps: 300

exp_name: "object_react_gt_benchmark"

run_list: ''
path_run: ''

method: 'learnt'
segmentor: 'sim'
goal_source: 'gt_topometric'
graph_filename: null
infer_depth: False
infer_traversable: False
use_costmap_ema: False
inject_costmap_noise: False
ema_lambda: 0.7
noise_prob: 0.2

log_wandb: False
log_robot: True
debug: False
except_exit: False

plot: False
save_vis: False

cull_qry_instances: False
cull_map_instances: False
cull_map_method: 'sim'
cull_map_strategy: 'edge_remove'

sim:
  hfov: 120
  width: 320
  height: 240
  sensor_height: 0.4
  sensor_height_map: 1.31

goal_gen:
  textLabels: []
  map_segmentor_name: "sim"
  matcher_name: "lightglue"
  map_matcher_name: "lightglue"
  geometric_verification: True
  match_area: False
  edge_weight_str: "e3d"
  goalNodeIdx: null
  use_goal_nbrs: False
  plan_da_nbrs: False
  preplan_to_goals_only: False
  rewrite_graph_with_allPathLengths: False
  loc_radius: 16
  subsample_ref: 2
  reloc_rad_add: 2
  reloc_rad_max: 15
  min_num_matches: 0
  offset_localizedImgIdx: 0
  do_track: True

controller:
  config_file: "configs/controller/object_react_controller.yaml"
  v_min: 0.05
  v_max: 0.2
  w_min: -0.3
  w_max: 0.3
